"""initial schema

Revision ID: a4decaa46555
Revises: 
Create Date: 2026-06-24 03:48:15.343909
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4decaa46555'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalog',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game', sa.String(), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('set_code', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('image_path', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game', 'language', 'set_code', 'kind', name='uq_catalog_sku')
    )
    op.create_table('sets',
    sa.Column('game', sa.String(), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('set_code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('abbreviation', sa.String(), nullable=True),
    sa.Column('series', sa.String(), nullable=True),
    sa.Column('release_date', sa.String(), nullable=True),
    sa.Column('logo_url', sa.String(), nullable=True),
    sa.Column('symbol_url', sa.String(), nullable=True),
    sa.Column('card_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('game', 'language', 'set_code')
    )
    with op.batch_alter_table('sets', schema=None) as batch_op:
        batch_op.create_index('idx_sets_game_lang', ['game', 'language'], unique=False)

    op.create_table('sites',
    sa.Column('host', sa.String(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('games', sa.String(), nullable=True),
    sa.Column('active', sa.Integer(), nullable=False),
    sa.Column('first_seen_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('host')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('shop', sa.String(), nullable=False),
    sa.Column('platform_pid', sa.String(), nullable=False),
    sa.Column('game', sa.String(), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('set_code', sa.String(), nullable=False),
    sa.Column('set_codes', sa.String(), nullable=True),
    sa.Column('series', sa.String(), nullable=True),
    sa.Column('kind', sa.String(), nullable=True),
    sa.Column('catalog_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('first_seen_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['catalog_id'], ['catalog.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform', 'shop', 'platform_pid', name='uq_product_identity')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index('idx_products_game_lang_set', ['game', 'language', 'set_code'], unique=False)

    op.create_table('alert_configs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('scope_type', sa.String(length=16), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('catalog_id', sa.Integer(), nullable=True),
    sa.Column('set_code', sa.String(length=32), nullable=True),
    sa.Column('game', sa.String(length=32), nullable=True),
    sa.Column('language', sa.String(length=8), nullable=True),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('destination', sa.String(length=512), nullable=False),
    sa.Column('alert_type', sa.String(length=16), nullable=False),
    sa.Column('price_threshold', sa.Float(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['catalog_id'], ['catalog.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alert_configs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alert_configs_user_id'), ['user_id'], unique=False)

    op.create_table('favorites',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('catalog_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['catalog_id'], ['catalog.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'catalog_id', name='uq_fav_user_catalog'),
    sa.UniqueConstraint('user_id', 'product_id', name='uq_fav_user_product')
    )
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_favorites_user_id'), ['user_id'], unique=False)

    op.create_table('snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('observed_at', sa.String(), nullable=False),
    sa.Column('price_eur', sa.Float(), nullable=True),
    sa.Column('available', sa.Integer(), nullable=True),
    sa.Column('raw_variant_count', sa.Integer(), nullable=True),
    sa.Column('stock_remaining', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('snapshots', schema=None) as batch_op:
        batch_op.create_index('idx_snapshots_product_time', ['product_id', 'observed_at'], unique=False)

    op.create_table('alert_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('alert_config_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=16), nullable=False),
    sa.Column('trigger_observed_at', sa.String(length=40), nullable=False),
    sa.Column('price_eur', sa.Float(), nullable=True),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('sent_ok', sa.Boolean(), nullable=False),
    sa.Column('error', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['alert_config_id'], ['alert_configs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alert_events', schema=None) as batch_op:
        batch_op.create_index('idx_alert_event_dedup', ['alert_config_id', 'product_id', 'event_type', 'trigger_observed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_alert_events_alert_config_id'), ['alert_config_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alert_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alert_events_alert_config_id'))
        batch_op.drop_index('idx_alert_event_dedup')

    op.drop_table('alert_events')
    with op.batch_alter_table('snapshots', schema=None) as batch_op:
        batch_op.drop_index('idx_snapshots_product_time')

    op.drop_table('snapshots')
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_favorites_user_id'))

    op.drop_table('favorites')
    with op.batch_alter_table('alert_configs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alert_configs_user_id'))

    op.drop_table('alert_configs')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index('idx_products_game_lang_set')

    op.drop_table('products')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('sites')
    with op.batch_alter_table('sets', schema=None) as batch_op:
        batch_op.drop_index('idx_sets_game_lang')

    op.drop_table('sets')
    op.drop_table('catalog')
    # ### end Alembic commands ###
