"""waitlist signups (collecte e-mails de la landing)

Table autonome : pas de FK vers `users`, un inscrit waitlist n'a pas de compte.
L'index unique sur `email` est ce qui rend `POST /waitlist` idempotent.

Revision ID: a9c573058c1d
Revises: b7c1d2e3f4a5
Create Date: 2026-08-17 00:41:18.894438
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9c573058c1d'
down_revision: Union[str, None] = 'b7c1d2e3f4a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('waitlist_signups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('waitlist_signups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_waitlist_signups_email'), ['email'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('waitlist_signups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_waitlist_signups_email'))

    op.drop_table('waitlist_signups')
    # ### end Alembic commands ###
